# Generated by Django 6.1.1 on 2026-09-26 07:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("photo_key", models.CharField(blank=True, max_length=300)),
                ("same_as", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "availabilities",
                "ordering": ("sort_order", "slug"),
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("logo_key", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "slug"),
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="LearningBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "main categories",
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("gtin", models.CharField(blank=True, max_length=14)),
                (
                    "price_official",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_checked_at", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "age_min_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "age_max_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "usage_lifespan_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
        migrations.CreateModel(
            name="ProsConType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "slug"),
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="ServerRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "slug"),
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "slug"),
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_name", models.CharField(blank=True, max_length=60)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "sub-categories",
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="AmpelScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "ordering": ("value",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("value__gte", 1), ("value__lte", 3)),
                        name="ampel_score_between_1_and_3",
                    )
                ],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=2, unique=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ("code",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^[A-Z]{2}$")),
                        name="country_code_is_iso_alpha2",
                    )
                ],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="SchoolProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jenymia.product",
                    ),
                ),
                ("is_child_certified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "school product",
            },
            bases=("jenymia.product", models.Model),
        ),
        migrations.CreateModel(
            name="TechProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jenymia.product",
                    ),
                ),
                ("is_offline_capable", models.BooleanField(default=False)),
                ("requires_account", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "tech product",
            },
            bases=("jenymia.product",),
        ),
        migrations.CreateModel(
            name="ToysProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jenymia.product",
                    ),
                ),
                ("is_child_certified", models.BooleanField(default=False)),
                (
                    "learning_badges",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="jenymia.learningbadge"
                    ),
                ),
            ],
            options={
                "verbose_name": "toys product",
            },
            bases=("jenymia.product", models.Model),
        ),
        migrations.AddField(
            model_name="product",
            name="ampel_score",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="jenymia.ampelscore",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="jenymia.author",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="badges",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="jenymia.badge"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="jenymia.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufactured_in_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="jenymia.country",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="jenymia.maincategory",
            ),
        ),
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=60)),
                ("url", models.URLField(max_length=1000)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "availability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affiliate_links",
                        to="jenymia.availability",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_links",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductFaq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=300)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manufacturer", "manufacturer"),
                            ("amazon_paapi", "Amazon PA-API"),
                            ("awin", "Awin"),
                            ("own_photo", "own photo"),
                            ("stock_licensed", "licensed stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductImageTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("alt_text", models.CharField(max_length=200)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("license_note", models.TextField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductProsCon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pros_cons",
                        to="jenymia.product",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pros_cons",
                        to="jenymia.proscontype",
                    ),
                ),
            ],
            options={
                "ordering": ("type", "sort_order"),
            },
        ),
        migrations.CreateModel(
            name="ProductProsConTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "pros_con",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productproscon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=60)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductSpecTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=300)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productspec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductToAnalyse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("text_extracted", "text extracted"),
                            ("analyse_complete", "analysis complete"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("prompt_version", models.CharField(blank=True, max_length=120)),
                ("llm_provider", models.CharField(blank=True, max_length=20)),
                ("llm_model", models.CharField(blank=True, max_length=60)),
                ("last_analysed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysed_by",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")], max_length=10
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_to_analyse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_orders",
                        to="jenymia.maincategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_orders",
                        to="jenymia.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="jenymia.producttoanalyse",
            ),
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("slug", models.SlugField(max_length=160)),
                ("title", models.CharField(max_length=200)),
                ("hook", models.CharField(max_length=300)),
                ("description_short", models.TextField()),
                ("description_detail", models.TextField()),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                ("summary", models.TextField(blank=True)),
                ("verdict", models.CharField(blank=True, max_length=300)),
                ("question_headline", models.CharField(blank=True, max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProsConTypeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "pros_con_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.proscontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_optional", models.BooleanField(default=False)),
                ("third_party_sharing", models.BooleanField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_categories",
                        to="jenymia.datatype",
                    ),
                ),
                (
                    "server_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_categories",
                        to="jenymia.serverregion",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_categories",
                        to="jenymia.techproduct",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "data categories",
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ServerRegionTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "server_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.serverregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=300)),
                ("url", models.URLField(max_length=1000)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="jenymia.product",
                    ),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_sources",
                        to="jenymia.sourcetype",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="SourceTypeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.sourcetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sub_categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="jenymia.subcategory"
            ),
        ),
        migrations.CreateModel(
            name="SubCategoryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=100)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.subcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "extract_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("extracted", "extracted"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("final_url", models.URLField(blank=True, max_length=1000)),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.URLField(blank=True, max_length=1000)),
                ("site_name", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("headings", models.JSONField(blank=True, default=list)),
                ("jsonld", models.JSONField(blank=True, default=list)),
                ("opengraph", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_urls",
                        to="jenymia.producttoanalyse",
                    ),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("slug", "youtube"), _negated=True),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="web_urls",
                        to="jenymia.sourcetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YoutubeUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "extract_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("extracted", "extracted"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("video_id", models.CharField(blank=True, max_length=20)),
                ("webpage_url", models.URLField(blank=True, max_length=500)),
                ("channel", models.CharField(blank=True, max_length=200)),
                ("channel_id", models.CharField(blank=True, max_length=60)),
                ("channel_url", models.URLField(blank=True, max_length=500)),
                ("upload_date", models.DateField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("license", models.CharField(blank=True, max_length=120)),
                ("availability", models.CharField(blank=True, max_length=60)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("chapters", models.JSONField(blank=True, default=list)),
                ("transcript_language", models.CharField(blank=True, max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_urls",
                        to="jenymia.producttoanalyse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AmpelScoreTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "ampel_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.ampelscore",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ampel_score", "locale"),
                        name="ampel_score_one_label_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("bio", models.TextField(blank=True)),
                ("credentials", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.author",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "locale"),
                        name="author_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.availability",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("availability", "locale"),
                        name="availability_one_label_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BadgeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.badge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("badge", "locale"),
                        name="badge_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CountryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.country",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "locale"),
                        name="country_one_label_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataCategoryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "data_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.datacategory",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data_category", "locale"),
                        name="data_category_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataTypeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.datatype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data_type", "locale"),
                        name="data_type_one_label_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningBadgeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "learning_badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.learningbadge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learning_badge", "locale"),
                        name="learning_badge_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MainCategoryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=100)),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.maincategory",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("main_category", "locale"),
                        name="main_category_one_translation_per_locale",
                    ),
                    models.UniqueConstraint(
                        fields=("locale", "slug"),
                        name="main_category_slug_unique_per_locale",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolProductTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("safety_short", models.TextField(blank=True)),
                ("safety_long", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_translations",
                        to="jenymia.schoolproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechProductTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("privacy_short", models.TextField(blank=True)),
                ("privacy_long", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_translations",
                        to="jenymia.techproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToysProductTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("safety_short", models.TextField(blank=True)),
                ("safety_long", models.TextField(blank=True)),
                ("growth_info", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_translations",
                        to="jenymia.toysproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFaqTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productfaq",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faq", "locale"), name="faq_one_translation_per_locale"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="product_one_primary_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimagetranslation",
            constraint=models.UniqueConstraint(
                fields=("image", "locale"), name="image_one_translation_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="productproscontranslation",
            constraint=models.UniqueConstraint(
                fields=("pros_con", "locale"),
                name="pros_con_one_translation_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="productspec",
            constraint=models.UniqueConstraint(
                fields=("product", "key"), name="product_spec_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productspectranslation",
            constraint=models.UniqueConstraint(
                fields=("spec", "locale"), name="spec_one_translation_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttranslation",
            constraint=models.UniqueConstraint(
                fields=("product", "locale"), name="product_one_translation_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttranslation",
            constraint=models.UniqueConstraint(
                fields=("locale", "slug"), name="product_slug_unique_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="proscontypetranslation",
            constraint=models.UniqueConstraint(
                fields=("pros_con_type", "locale"),
                name="pros_con_type_one_label_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="serverregiontranslation",
            constraint=models.UniqueConstraint(
                fields=("server_region", "locale"),
                name="server_region_one_label_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcetypetranslation",
            constraint=models.UniqueConstraint(
                fields=("source_type", "locale"),
                name="source_type_one_label_per_locale",
            ),
        ),
        migrations.AddIndex(
            model_name="producttoanalyse",
            index=models.Index(fields=["status"], name="jenymia_pro_status_58008c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "-published_at"],
                name="jenymia_pro_is_publ_f22a47_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age_min_months__isnull", True),
                    ("age_max_months__isnull", True),
                    ("age_min_months__lte", models.F("age_max_months")),
                    _connector="OR",
                ),
                name="product_age_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        ("ampel_score__isnull", False), ("published_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="product_published_requires_score_and_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategorytranslation",
            constraint=models.UniqueConstraint(
                fields=("sub_category", "locale"),
                name="sub_category_one_translation_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategorytranslation",
            constraint=models.UniqueConstraint(
                fields=("locale", "slug"), name="sub_category_slug_unique_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="weburl",
            constraint=models.UniqueConstraint(
                fields=("product", "url"), name="jenymia_weburl_url_unique_per_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="youtubeurl",
            constraint=models.UniqueConstraint(
                fields=("product", "url"),
                name="jenymia_youtubeurl_url_unique_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolproducttranslation",
            constraint=models.UniqueConstraint(
                fields=("product", "locale"), name="school_product_one_text_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="techproducttranslation",
            constraint=models.UniqueConstraint(
                fields=("product", "locale"), name="tech_product_one_text_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="toysproducttranslation",
            constraint=models.UniqueConstraint(
                fields=("product", "locale"), name="toys_product_one_text_per_locale"
            ),
        ),
    ]
