# Generated by Django 6.1.1 on 2026-09-24 20:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("bio", models.TextField(blank=True)),
                ("credentials", models.TextField(blank=True)),
                ("photo_key", models.CharField(blank=True, max_length=300)),
                ("same_as", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("logo_key", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="LearningBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("toys", "Spielen & Lernen"),
                            ("school", "Schule & Alltag"),
                            ("tech", "Tech & Sicherheit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="jenymia.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("gtin", models.CharField(blank=True, max_length=14)),
                (
                    "ampel_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "price_current",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_original",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "age_min_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "age_max_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "usage_lifespan_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("manufactured_in_country", models.CharField(blank=True, max_length=2)),
                ("is_offline_capable", models.BooleanField(default=False)),
                ("requires_account", models.BooleanField(default=False)),
                ("is_child_certified", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="jenymia.author",
                    ),
                ),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="jenymia.badge"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="jenymia.brand",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="jenymia.category"
                    ),
                ),
                (
                    "learning_badges",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="jenymia.learningbadge"
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
        migrations.CreateModel(
            name="DataCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("location", "location"),
                            ("audio", "audio"),
                            ("video", "video"),
                            ("contacts", "contacts"),
                            ("usage_stats", "usage statistics"),
                            ("biometrics", "biometrics"),
                            ("messages", "messages"),
                            ("photos", "photos"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "server_region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EU", "EU"),
                            ("US", "US"),
                            ("CN", "CN"),
                            ("third_country", "third country"),
                            ("unknown", "unknown"),
                            ("on_device_only", "on device only"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("third_party_sharing", models.BooleanField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_categories",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "data categories",
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=60)),
                ("url", models.URLField(max_length=1000)),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_stock", "in stock"),
                            ("out_of_stock", "out of stock"),
                            ("preorder", "preorder"),
                            ("discontinued", "discontinued"),
                        ],
                        max_length=15,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_links",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductFaq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=300)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manufacturer", "manufacturer"),
                            ("amazon_paapi", "Amazon PA-API"),
                            ("awin", "Awin"),
                            ("own_photo", "own photo"),
                            ("stock_licensed", "licensed stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_note", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductImageTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("alt_text", models.CharField(max_length=200)),
                ("caption", models.CharField(blank=True, max_length=300)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductProsCon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("pro", "pro"), ("con", "con")], max_length=3
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pros_cons",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("type", "sort_order"),
            },
        ),
        migrations.CreateModel(
            name="ProductProsConTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "pros_con",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productproscon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=300)),
                ("url", models.URLField(max_length=1000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("article", "article"),
                            ("test_institute", "test institute"),
                            ("manufacturer", "manufacturer"),
                            ("forum", "forum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=60)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="jenymia.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductSpecTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("value", models.CharField(max_length=300)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productspec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductToAnalyse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("text_extracted", "text extracted"),
                            ("analyse_complete", "analysis complete"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("prompt_version", models.CharField(blank=True, max_length=60)),
                ("last_analysed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysed_by",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_orders",
                        to="jenymia.category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_to_analyse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="jenymia.producttoanalyse",
            ),
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("slug", models.SlugField(max_length=160)),
                ("title", models.CharField(max_length=200)),
                ("hook", models.CharField(max_length=300)),
                ("description_short", models.TextField()),
                ("description_detail", models.TextField()),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                ("summary", models.TextField(blank=True)),
                ("verdict", models.CharField(blank=True, max_length=300)),
                ("question_headline", models.CharField(blank=True, max_length=200)),
                ("safety_short", models.TextField(blank=True)),
                ("safety_long", models.TextField(blank=True)),
                ("growth_info", models.TextField(blank=True)),
                ("privacy_short", models.TextField(blank=True)),
                ("privacy_long", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "extract_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("extracted", "extracted"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("article", "article"),
                            ("test_institute", "test institute"),
                            ("manufacturer", "manufacturer"),
                            ("forum", "forum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("final_url", models.URLField(blank=True, max_length=1000)),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.URLField(blank=True, max_length=1000)),
                ("site_name", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("headings", models.JSONField(blank=True, default=list)),
                ("jsonld", models.JSONField(blank=True, default=list)),
                ("opengraph", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_urls",
                        to="jenymia.producttoanalyse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YoutubeUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "extract_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("extracted", "extracted"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("video_id", models.CharField(blank=True, max_length=20)),
                ("webpage_url", models.URLField(blank=True, max_length=500)),
                ("channel", models.CharField(blank=True, max_length=200)),
                ("channel_id", models.CharField(blank=True, max_length=60)),
                ("channel_url", models.URLField(blank=True, max_length=500)),
                ("upload_date", models.DateField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("license", models.CharField(blank=True, max_length=120)),
                ("availability", models.CharField(blank=True, max_length=60)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("chapters", models.JSONField(blank=True, default=list)),
                ("transcript_language", models.CharField(blank=True, max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_urls",
                        to="jenymia.producttoanalyse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BadgeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.badge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("badge", "locale"),
                        name="badge_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.category",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "locale"),
                        name="category_one_translation_per_locale",
                    ),
                    models.UniqueConstraint(
                        fields=("locale", "slug"),
                        name="category_slug_unique_per_locale",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataCategoryTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "data_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.datacategory",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data_category", "locale"),
                        name="data_category_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningBadgeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "learning_badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.learningbadge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learning_badge", "locale"),
                        name="learning_badge_one_translation_per_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFaqTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=2
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jenymia.productfaq",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faq", "locale"), name="faq_one_translation_per_locale"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="product_one_primary_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimagetranslation",
            constraint=models.UniqueConstraint(
                fields=("image", "locale"), name="image_one_translation_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="productproscontranslation",
            constraint=models.UniqueConstraint(
                fields=("pros_con", "locale"),
                name="pros_con_one_translation_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="productspec",
            constraint=models.UniqueConstraint(
                fields=("product", "key"), name="product_spec_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productspectranslation",
            constraint=models.UniqueConstraint(
                fields=("spec", "locale"), name="spec_one_translation_per_locale"
            ),
        ),
        migrations.AddIndex(
            model_name="producttoanalyse",
            index=models.Index(fields=["status"], name="jenymia_pro_status_58008c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "-published_at"],
                name="jenymia_pro_is_publ_f22a47_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ampel_score__isnull", True),
                    models.Q(("ampel_score__gte", 1), ("ampel_score__lte", 3)),
                    _connector="OR",
                ),
                name="product_ampel_score_between_1_and_3",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age_min_months__isnull", True),
                    ("age_max_months__isnull", True),
                    ("age_min_months__lte", models.F("age_max_months")),
                    _connector="OR",
                ),
                name="product_age_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manufactured_in_country", ""),
                    ("manufactured_in_country__regex", "^[A-Z]{2}$"),
                    _connector="OR",
                ),
                name="product_country_is_iso_alpha2",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        ("ampel_score__isnull", False), ("published_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="product_published_requires_score_and_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="producttranslation",
            constraint=models.UniqueConstraint(
                fields=("product", "locale"), name="product_one_translation_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttranslation",
            constraint=models.UniqueConstraint(
                fields=("locale", "slug"), name="product_slug_unique_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="weburl",
            constraint=models.UniqueConstraint(
                fields=("product", "url"), name="jenymia_weburl_url_unique_per_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="youtubeurl",
            constraint=models.UniqueConstraint(
                fields=("product", "url"),
                name="jenymia_youtubeurl_url_unique_per_order",
            ),
        ),
    ]
